### ISSUE TITLE
error while using with angular project

### ISSUE THREAD

**Issue by h20003** [anurag-roy/kiteconnect-ts#14]
ws__WEBPACK_IMPORTED_MODULE_ WebSocket is not a constructor

**Comment by anurag-roy** [comment]
Hi, browser environments are not supported currently by this library, only Node.js. But I do want to support browsers in the future.

**Comment by anurag-roy** [comment]
Just explored this a bit, and its not possible to make this library work on the browser.

Added a new [Browser Support section](https://github.com/anurag-roy/kiteconnect-ts#browser-support) in the README, detailing this.
