### ISSUE TITLE
KiteConnect Typescript

### ISSUE THREAD

**Issue by h20003** [anurag-roy/kiteconnect-ts#2]
Hello,
Thank you for sharing typescript version of kitetikcer. any plan for kiteconnect api in near future? also looing for alice blue's typescript version. i have tried but failed. 

Thanks

**Comment by anurag-roy** [comment]
Hi @h20003 , to be honest haven't had the time to work on KiteConnect but I do have plans to add it as well.

I'm not sure what you mean by alice blue's typescript version. Can you elaborate?

**Comment by h20003** [comment]
at the moment alice blue's api is python version only. i have started converting into typescript to use with Angular. by studying python source code of alice blue api i converted api to get order,price,etc.. and place and cancel orders via typescript code. but not able to convert websocket's code. it is similar to kiteticker but. having issue with it.

below is the link for python source code: https://github.com/krishnavelu/alice_blue.

please send me your email id so that i can share angular's typerscript version of aliceblye api.

Thanks

**Comment by anurag-roy** [comment]
I suggest you first take a look at the [official Kite API docs](https://kite.trade/docs/connect/v3/websocket/) if you want to write your own ticker.

Or shoot me an email anuragroy11@gmail.com if you're still having problems.

**Comment by ebinxavier** [comment]
@anurag-roy any updates on kiteConnect?

**Comment by anurag-roy** [comment]
Added KiteConnect in latest release #10
