### ISSUE TITLE
Broken documentation site

### ISSUE THREAD

**Issue by chintan100** [anurag-roy/kiteconnect-ts#27]
Hello, 

https://kiteconnect.anuragroy.dev is down. Can't open https://kiteconnect.anuragroy.dev/classes/KiteConnect. Can you check?

**Comment by anurag-roy** [comment]
@chintan100 Thanks for reporting!

Yes, I am aware, facing some problems with my domain which should get resolved soon.

Meanwhile, you can use this link: https://kiteconnect-ts.vercel.app/

**Comment by anurag-roy** [comment]
Fixed
